### PR TITLE
Add `jupyterlab-topbar-text` to `environment.yml`

### PR DESCRIPTION
**Pull request by jtpio**
Keeping as a draft while waiting for https://github.com/conda-forge/staged-recipes/pull/17189 to be merged

Testing with https://mybinder.org/v2/gh/jtpio/plasmabio-template-python/jupyterlab-topbar-text?urlpath=%2Flab/

### CODE REVIEW

**Comment by jtpio** [comment]
https://github.com/conda-forge/staged-recipes/pull/17189 has been merged, this is good to go.

**Comment by pierrepo** [comment]
Many thanks @jtpio :pray:

**Comment by jtpio** [comment]
@pierrepo this new repo layout using prebuilt extensions for JupyterLab 3.0 together with the latest `jupyterhub/repo2docker` image (powered by mamba) should now considerably speed up the image builds.

**Comment by pierrepo** [comment]
Thank you. I will broadcast these enhancements to other templates: [template-bash](https://github.com/plasmabio/template-bash) and [template-r](https://github.com/plasmabio/template-r)

**Pull request merged**
